/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulario;
import Principal.FrmPrincipal;
import Sesion.Sesion;
import Clases.Apertura;
import Clases.Ventas;
import Clases.CorteV;
/**
 *
 * @author mayka
 */
public class HomeVendedor extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public HomeVendedor() {
        initComponents();
        this.setTitle("Bienvenido a Home");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MenuSesion = new javax.swing.JMenu();
        btnCerrarSesion = new javax.swing.JMenuItem();
        MenuApertura = new javax.swing.JMenu();
        btnApertura = new javax.swing.JMenuItem();
        btnVentas = new javax.swing.JMenuItem();
        MenuBuscar = new javax.swing.JMenu();
        btnBuscar = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        btnCorte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuSesion.setText("Sesion");

        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        MenuSesion.add(btnCerrarSesion);

        jMenuBar1.add(MenuSesion);

        MenuApertura.setText("Apertura");

        btnApertura.setText("Aperturar caja");
        btnApertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAperturaActionPerformed(evt);
            }
        });
        MenuApertura.add(btnApertura);

        btnVentas.setText("Ventas");
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        MenuApertura.add(btnVentas);

        jMenuBar1.add(MenuApertura);

        MenuBuscar.setText("Buscar");

        btnBuscar.setText("Buscar producto");
        MenuBuscar.add(btnBuscar);

        jMenuBar1.add(MenuBuscar);

        jMenu1.setText("Corte");

        btnCorte.setText("Corte");
        btnCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorteActionPerformed(evt);
            }
        });
        jMenu1.add(btnCorte);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        Sesion.loginUsr(null,null,null,null,0);
        this.dispose();
        FrmPrincipal principal=new FrmPrincipal();
        principal.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnAperturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAperturaActionPerformed
        Apertura apertura=new Apertura(this,true);
        apertura.setVisible(true);
    }//GEN-LAST:event_btnAperturaActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        Ventas ventas=new Ventas(this,true);
        ventas.setVisible(true);
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorteActionPerformed
        CorteV corte=new CorteV(this,true);
        corte.setVisible(true);
    }//GEN-LAST:event_btnCorteActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuApertura;
    private javax.swing.JMenu MenuBuscar;
    private javax.swing.JMenu MenuSesion;
    private javax.swing.JMenuItem btnApertura;
    private javax.swing.JMenuItem btnBuscar;
    private javax.swing.JMenuItem btnCerrarSesion;
    private javax.swing.JMenuItem btnCorte;
    private javax.swing.JMenuItem btnVentas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
